### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by Adilmar** [soheillll/Skin-cancer-recoginition#2]
Hi Congratulations on the project, I have the following problem when I use above 2000 images I have numpy error in this line.

```
train_tensors = paths_to_tensor (train_files) .astype ('float32') / 255
valid_tensors = paths_to_tensor (valid_files) .astype ('float32') / 255
```

My computer is an i7 with 8gb have idea how to solve.

Regards

**Comment by soheil-mp** [comment]
Hey there! 

Sure. in here code will load all images into your memory and if you have a memory problem then you can use build-in data augmentation in Keras which it can be run even with weaker memory.
https://keras.io/preprocessing/image/

Good luck!
